// Boost.Signals library

// Copyright Timmo Stange 2007. Use, modification and
// distribution is subject to the Boost Software License, Version
// 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// For more information, see http://www.boost.org

#undef BOOST_SIGNALS_TEMPLATE_PARMS
#undef BOOST_SIGNALS_TEMPLATE_ARGS
#undef BOOST_SIGNALS_PARMS
#undef BOOST_SIGNALS_ARGS
#undef BOOST_SIGNALS_BOUND_ARGS
#undef BOOST_SIGNALS_SEMICOLON
#undef BOOST_SIGNALS_ARG_AS_MEMBER
#undef BOOST_SIGNALS_ARGS_AS_MEMBERS
#undef BOOST_SIGNALS_COPY_PARMS
#undef BOOST_SIGNALS_INIT_ARG
#undef BOOST_SIGNALS_INIT_ARGS
#undef BOOST_SIGNALS_ARG_TYPE
#undef BOOST_SIGNALS_ARG_TYPES
#undef BOOST_SIGNALS_TRAITS_ARG_TYPE
#undef BOOST_SIGNALS_TRAITS_ARG_TYPES
#undef BOOST_SIGNAL_FUNCTION_N_HEADER
#undef BOOST_SIGNALS_COMMA_IF_NONZERO_ARGS
#undef BOOST_SIGNALS_STANDARD_ARG_TYPES
#undef BOOST_SIGNALS_SIGNAL
#undef BOOST_SIGNALS_FUNCTION
#undef BOOST_SIGNALS_ARGS_STRUCT
#undef BOOST_SIGNALS_CALL_BOUND
#undef BOOST_SIGNALS_SELECT_SLOT_FUNCTION
#undef BOOST_SIGNALS_ARGS_STRUCT_INST

